### ISSUE TITLE
No alert when student try to escape while taking test

### ISSUE THREAD

**Issue by nhocbounce** [hwngng/highschool-mcq#59]
không có alert khi học sinh có ý định thoát trang mà lưu bài làm luôn

**Comment by hwngng** [comment]
@nhocbounce không cần đâu

**Comment by nhocbounce** [comment]
@hwngng t nghĩ là cần chứ vì mình có thanh menu bar trong màn hình bài thi mà. Bấm nhầm vào bất cứ đâu là cx coi như đi cả bài luôn
