### ISSUE TITLE
Allow multiple correct answer

### ISSUE THREAD

**Issue by nhocbounce** [hwngng/highschool-mcq#62]
M đang để ở làm test là chỉ chọn 1 đáp án đúng cơ mà tạo câu hỏi thì nó có thể có nhiều hơn 1 đáp án đúng

**Comment by hwngng** [comment]
@nhocbounce thồi, ko hỗ trợ cái đấy

**Comment by nhocbounce** [comment]
Ơ. Quan trọng là giờ lúc tạo câu hỏi nó cho phép tạo câu hỏi có nhiều đáp án đúng. Nếu giờ ko như thế thì m chỉnh cái phần tạo câu hỏi đi, sao cho khi tạo chỉ có 1 đáp án đúng ý
